server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${IAM_DB_HOST:localhost}:${IAM_DB_PORT:5432}/${IAM_DB_NAME:vankoo_iam_db_dev}
    username: ${IAM_DB_USERNAME:admin}
    password: ${IAM_DB_PASSWORD:password}
  cloud:
    function:
      definition: userCreatedConsumer # Definimos el bean que actuará como consumidor de mensajes
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
          auto-create-topics: true
      bindings:
        # Este nombre debe coincidir con el del streamBridge.send()
        userCreated-out-0:
          destination: vankoo.iam.user.created
          content-type: application/json

eureka:
  instance:
    prefer-ip-address: false # En desarrollo, no es necesario usar IP, el hostname funciona bien
  client:
    register-with-eureka: true # Buscamos registrarnos en Eureka
    fetch-registry: true # Queremos obtener la lista de servicios registrados para poder comunicarnos con ellos
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/} # En desarrollo, apuntamos a localhost para Eureka
management:
  endpoints:
    web:
      exposure:
        # En desarrollo, exponemos solo los endpoints de salud e info por temas de seguridad, pero también para no saturar el log
        include: "health,info" # Importante para que Eureka vea el estado del IAM