spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${IAM_DB_PORT:5432}/${IAM_DB_NAME:vankoo_iam_db_dev}
    username: ${IAM_DB_USER:admin}
    password: ${IAM_DB_PASSWORD:password}
  cloud:
    function:
      definition: userCreatedConsumer # Definimos el bean que actuará como consumidor de mensajes
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
          auto-create-topics: true
      bindings:
        # Este nombre debe coincidir con el del streamBridge.send()
        userCreated-out-0:
          destination: vankoo.iam.user.created
          content-type: application/json

server:
  port: 8081